level Novice {
    title: "Novice"
    value: 1
}
  
level Weak {
    title:"Weak"
    value: 2
    competence: [Novice:100%, Weak:49%]
}
  
level Toddler {
    title:"Toddler"
    value: 3
    competence: [Novice:100%, Weak:65%]
}
 
level Ripe {
    title:"Ripe"
    value: 4
    competence: [Novice:100%, Weak:75%]
}
 
level Perfect {
    title:"Perfect"
    value: 5
    competence: [Novice:100%, Weak:85%]
}